sudo: false
language: php
php:
  - 5.6
  - 7.0

install:
  - composer install

script:
  - ./vendor/bin/phpcs --standard=./vendor/behance/php-sniffs/Behance/ruleset.xml ./src ./tests
  #- php scripts/phpcs --config-set php_path php; fi
  #- php ./vendor/squizlabs/php_codesniffer/scripts/phpcs ./vendor/squizlabs/php_codesniffer/CodeSniffer.php CodeSniffer --standard=PHPCS --report=summary -np
  #- pear package-validate package.xml; fi
  #- php scripts/build-phar.php; fi
  #- php phpcs.phar CodeSniffer.php CodeSniffer --standard=PHPCS --report=summary -np; fi
